/*
 * This source file was generated by the Gradle 'init' task
 */
package org.digmz;

import org.digmz.game.*;

public class Main {
    public String getGreeting() {
        return "Hello Branch";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
        Window.get().run();
    }
}
